---
info:
  title: Metasploit Concern
  description: Loads `ActiveSupport::Concern`s from `app/concerns` and and includes
    them in the appropriate class using `ActiveSupport.on_load(<underscored_class_name>)`.
  x-cortex-git:
    github:
      alias: r7org
      repository: rapid7/metasploit-concern
  x-cortex-tag: metasploit-concern
  x-cortex-type: service
  x-cortex-domain-parents:
  - tag: metasploit
  x-cortex-groups:
  - exposure:external-ship
openapi: 3.0.1
servers:
- url: "/"
